### ISSUE TITLE
dlib detector fails to work on fresh install Linux

### ISSUE THREAD

**Issue by jabooth** [menpo/menpodetect#12]
Due to the `jpeg` lack of pinning. Solution:
``` 
conda install jpeg=8
```
After install.

See also: https://github.com/menpo/cyffld2/issues/6

**Comment by patricksnape** [comment]
Damn, the jpeg update is a pain

**Comment by jabooth** [comment]
Yeah it would be great to move the burden of most/all our dependencies to `conda-forge`.

What's the issue again? Missing deps in some cases still? Is `conda-forge` still all done without `mkl`? That could be a major perf issue for `menpo3d` (suitesparse). Although there seems to be a well maintained feedstock for it... 

https://github.com/conda-forge/suitesparse-feedstock

Only other issue is minor change to `condaci` but that shoudn't be a big deal.

**Comment by patricksnape** [comment]
Windows windows windows. If we bin windows then we would be fine...

**Comment by jabooth** [comment]
Windows is a mess for conda-forge now - do you think that will improve in the next 3-6 months?

I could stomach the latest version of menpo being unavailable on Windows for a few months - a permanent dropping of support is a much more difficult pill to swallow...

**Comment by patricksnape** [comment]
Windows is just such a grim customer. Would require a lot of time to put in to pull it back up to scratch which I'm short on at the moment unfortunately

**Comment by jabooth** [comment]
@patricksnape not suggesting at all that you do it!

bottom line, big benefit of conda-forge is that lots of others are going to be addressing all these issues, so rather than us (and let's face it, often you!) having to get all our deps singing on all platforms, we let the community largely do it for us (with us pitching in where we need to).

My understanding is, we could start releasing mac/linux builds of all of menpo on conda-forge right now. Some of our deps would be newer (yay), we'd no longer need to maintain them ourselves (woo!), and we might even start benefiting from conda-forge exclusive builds (I'm thinking sksparse for mac).

Downside is, from numpy up, conda-forge is just a mess for windows.

If the community will be able to sort this stuff out in 2017, then moving sooner rather than later is fine in my eyes. Next few releases of menpo on conda might be mac/linux only, just while conda-forge for win sorts itself out.

If the community has been grappling with this for ages and there is no end in sight, we'd have to weigh up how important long-term windows support is to us.

**Comment by patricksnape** [comment]
Moving to conda-forge is happening as we speak
