### ISSUE TITLE
menpodetect import error for dlib, ffld2

### ISSUE THREAD

**Issue by rsln-s** [menpo/menpodetect#15]
I think there's something broken with loading of pretrained face detectors.

When I try:
`from menpodetect import load_opencv_frontal_face_detector`
or
`from menpodetect import load_pico_frontal_face_detector`

everything works fine. However,
`from menpodetect import load_ffld2_frontal_face_detector`
and
`from menpodetect import load_dlib_frontal_face_detector`

result in 

`ImportError: cannot import name 'load_dlib_frontal_face_detector'`

All setup as described in [AAM tutorial](http://www.menpo.org/menpofit/aam.html). Anaconda 4.4.11, Python 3.5.5 :: Anaconda, Inc.

**Comment by patricksnape** [comment]
Have you installed dlib and cyffld2?

**Comment by rsln-s** [comment]
I've installed dlib as described [here for python interface](http://dlib.net/compile.html), however even before that dlib has been installed; it seems to be shipped with menpo in coda environment:
`$ conda list`
`...`
`decorator                 4.2.1                    py35_0`
`dlib                      18.18                    py35_2    menpo`
`dlib                      19.9.0                    <pip>`
`docopt                    0.6.2                    py35_0`
`...`

When I try to `import dlib`, I get `ImportError: libjpeg.so.8: cannot open shared object file: No such file or directory`. I do have `libjpeg.so.9` and am having a bit of hard time figuring out how to downgrade it. Any suggestions?

**Comment by patricksnape** [comment]
Yeah that's your problem, you can't install dlib with conda and pip.

Run the following commands

```
conda remove dlib -y
pip uninstall dlib
conda install -c conda-forge dlib
```

Then try again. You may find that conda-forge replaces lots of defaults packages.

**Comment by rsln-s** [comment]
Thank you, Patrick! This works like a charm. 

I'm still not sure what went wrong though. Was it because menpo conda environment had the wrong (old) version of dlib?

**Comment by patricksnape** [comment]
pip and conda don't play well together. They will happily overwrite each other's package regardless of the versions. conda in particular will not respect pip. pip will respect newer packages but as you noted the currently uploaded dlib for menpo is older than the latest release on pip.
